version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install boto3 sagemaker pandas fsspec s3fs

  build:
    commands:
      - pwd
      - echo "Starting SageMaker Model Monitor setup..."
      - mv axcess-Mlops/modelretraining/retraining.py axcess-Mlops/
      - |
        python axcess-Mlops/retraining.py \
          --default-bucket ${ml_s3_bucket} \
          --model-package-group-name ${use_case} \
          --kwargs "{\"model_package_group_name_input\":\"${model_package_group_name_input}\",\"model_version_input\":\"${model_version_input}\",\"ml_s3_bucket\":\"${ml_s3_bucket}\",\"use_case\":\"${use_case}\"}"

